/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as EnquireNowRouteImport } from './routes/enquire-now'
import { Route as DesertSafariRouteImport } from './routes/desert-safari'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CityToursRouteImport } from './routes/city-tours'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttractionsRouteImport } from './routes/attractions'
import { Route as AdventuresRouteImport } from './routes/adventures'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as BookingSuccessRouteImport } from './routes/booking.success'
import { Route as BookingCancelledRouteImport } from './routes/booking.cancelled'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as AuthenticatedAdminToursRouteImport } from './routes/_authenticated/admin.tours'
import { Route as AuthenticatedAdminPostsRouteImport } from './routes/_authenticated/admin.posts'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'

const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireNowRoute = EnquireNowRouteImport.update({
  id: '/enquire-now',
  path: '/enquire-now',
  getParentRoute: () => rootRouteImport,
} as any)
const DesertSafariRoute = DesertSafariRouteImport.update({
  id: '/desert-safari',
  path: '/desert-safari',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CityToursRoute = CityToursRouteImport.update({
  id: '/city-tours',
  path: '/city-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionsRoute = AttractionsRouteImport.update({
  id: '/attractions',
  path: '/attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresRoute = AdventuresRouteImport.update({
  id: '/adventures',
  path: '/adventures',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToursRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToursRoute,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking/success',
  path: '/booking/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCancelledRoute = BookingCancelledRouteImport.update({
  id: '/booking/cancelled',
  path: '/booking/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminToursRoute = AuthenticatedAdminToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPostsRoute = AuthenticatedAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adventures': typeof AdventuresRoute
  '/attractions': typeof AttractionsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/city-tours': typeof CityToursRoute
  '/contact': typeof ContactRoute
  '/desert-safari': typeof DesertSafariRoute
  '/enquire-now': typeof EnquireNowRoute
  '/packages': typeof PackagesRoute
  '/premium': typeof PremiumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours': typeof ToursRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/booking/cancelled': typeof BookingCancelledRoute
  '/booking/success': typeof BookingSuccessRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/tours': typeof AuthenticatedAdminToursRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adventures': typeof AdventuresRoute
  '/attractions': typeof AttractionsRoute
  '/auth': typeof AuthRoute
  '/city-tours': typeof CityToursRoute
  '/contact': typeof ContactRoute
  '/desert-safari': typeof DesertSafariRoute
  '/enquire-now': typeof EnquireNowRoute
  '/packages': typeof PackagesRoute
  '/premium': typeof PremiumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/booking/cancelled': typeof BookingCancelledRoute
  '/booking/success': typeof BookingSuccessRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/blog': typeof BlogIndexRoute
  '/tours': typeof ToursIndexRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/tours': typeof AuthenticatedAdminToursRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/adventures': typeof AdventuresRoute
  '/attractions': typeof AttractionsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/city-tours': typeof CityToursRoute
  '/contact': typeof ContactRoute
  '/desert-safari': typeof DesertSafariRoute
  '/enquire-now': typeof EnquireNowRoute
  '/packages': typeof PackagesRoute
  '/premium': typeof PremiumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours': typeof ToursRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/booking/cancelled': typeof BookingCancelledRoute
  '/booking/success': typeof BookingSuccessRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/_authenticated/admin/tours': typeof AuthenticatedAdminToursRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adventures'
    | '/attractions'
    | '/auth'
    | '/blog'
    | '/city-tours'
    | '/contact'
    | '/desert-safari'
    | '/enquire-now'
    | '/packages'
    | '/premium'
    | '/sitemap.xml'
    | '/tours'
    | '/admin'
    | '/blog/$slug'
    | '/booking/cancelled'
    | '/booking/success'
    | '/tours/$slug'
    | '/blog/'
    | '/tours/'
    | '/admin/bookings'
    | '/admin/posts'
    | '/admin/tours'
    | '/api/stripe/webhook'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adventures'
    | '/attractions'
    | '/auth'
    | '/city-tours'
    | '/contact'
    | '/desert-safari'
    | '/enquire-now'
    | '/packages'
    | '/premium'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/booking/cancelled'
    | '/booking/success'
    | '/tours/$slug'
    | '/blog'
    | '/tours'
    | '/admin/bookings'
    | '/admin/posts'
    | '/admin/tours'
    | '/api/stripe/webhook'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/adventures'
    | '/attractions'
    | '/auth'
    | '/blog'
    | '/city-tours'
    | '/contact'
    | '/desert-safari'
    | '/enquire-now'
    | '/packages'
    | '/premium'
    | '/sitemap.xml'
    | '/tours'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/booking/cancelled'
    | '/booking/success'
    | '/tours/$slug'
    | '/blog/'
    | '/tours/'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/posts'
    | '/_authenticated/admin/tours'
    | '/api/stripe/webhook'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdventuresRoute: typeof AdventuresRoute
  AttractionsRoute: typeof AttractionsRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CityToursRoute: typeof CityToursRoute
  ContactRoute: typeof ContactRoute
  DesertSafariRoute: typeof DesertSafariRoute
  EnquireNowRoute: typeof EnquireNowRoute
  PackagesRoute: typeof PackagesRoute
  PremiumRoute: typeof PremiumRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToursRoute: typeof ToursRouteWithChildren
  BookingCancelledRoute: typeof BookingCancelledRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire-now': {
      id: '/enquire-now'
      path: '/enquire-now'
      fullPath: '/enquire-now'
      preLoaderRoute: typeof EnquireNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desert-safari': {
      id: '/desert-safari'
      path: '/desert-safari'
      fullPath: '/desert-safari'
      preLoaderRoute: typeof DesertSafariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city-tours': {
      id: '/city-tours'
      path: '/city-tours'
      fullPath: '/city-tours'
      preLoaderRoute: typeof CityToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions': {
      id: '/attractions'
      path: '/attractions'
      fullPath: '/attractions'
      preLoaderRoute: typeof AttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures': {
      id: '/adventures'
      path: '/adventures'
      fullPath: '/adventures'
      preLoaderRoute: typeof AdventuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof ToursRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof ToursRoute
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/booking/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/cancelled': {
      id: '/booking/cancelled'
      path: '/booking/cancelled'
      fullPath: '/booking/cancelled'
      preLoaderRoute: typeof BookingCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/tours': {
      id: '/_authenticated/admin/tours'
      path: '/tours'
      fullPath: '/admin/tours'
      preLoaderRoute: typeof AuthenticatedAdminToursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/posts': {
      id: '/_authenticated/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthenticatedAdminPostsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminPostsRoute: typeof AuthenticatedAdminPostsRoute
  AuthenticatedAdminToursRoute: typeof AuthenticatedAdminToursRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminPostsRoute: AuthenticatedAdminPostsRoute,
  AuthenticatedAdminToursRoute: AuthenticatedAdminToursRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ToursRouteChildren {
  ToursSlugRoute: typeof ToursSlugRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursSlugRoute: ToursSlugRoute,
  ToursIndexRoute: ToursIndexRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdventuresRoute: AdventuresRoute,
  AttractionsRoute: AttractionsRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CityToursRoute: CityToursRoute,
  ContactRoute: ContactRoute,
  DesertSafariRoute: DesertSafariRoute,
  EnquireNowRoute: EnquireNowRoute,
  PackagesRoute: PackagesRoute,
  PremiumRoute: PremiumRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToursRoute: ToursRouteWithChildren,
  BookingCancelledRoute: BookingCancelledRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
